services:
  postgres:
    image: postgres:16
    container_name: db-postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nextjs:
    build: .
    container_name: nextjs
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
