/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Krishu (https://sketchfab.com/manoj44)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/classic-round-side-table-2f88f788421047e9af9e2e93a047856b
Title: Classic round side table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Group } from 'three'

interface ModelProps {
  [key: string]: any
  onClick?: (mesh: Group) => void
}

export function Table({ onClick, ...props }: ModelProps) {
  const { nodes, materials } = useGLTF('/table/table.gltf') as any
  const tableRef = useRef<Group>(null)

  if (!nodes || !materials) return null

  return (
    <group
      {...props}
      ref={tableRef}
      onClick={() => {
        if (onClick && tableRef.current) {
          onClick(tableRef.current)
        }
      }}
    >
      {/* Tampo da mesa */}
      <group
        position={[0, 1.05, 0]} // Posição elevada para ficar em cima dos pés
        rotation={[-3.14, 0.275, -3.141]}
        scale={2}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6?.geometry}
          material={materials['plywood-cc0_platte.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7?.geometry}
          material={materials['plywood-cc0.001']}
        />
      </group>
      {/* Pés da mesa */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4?.geometry}
        material={materials['plywood-cc0.001']}
        position={[0.011, 0.086, 0.04]}
        rotation={[-Math.PI, 0.276, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9?.geometry}
        material={materials['plywood-cc0.001']}
        position={[0.011, 0.086, 0.04]}
        rotation={[Math.PI, -1.546, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11?.geometry}
        material={materials['plywood-cc0.001']}
        position={[0.011, 0.086, 0.04]}
        rotation={[0, 0.627, 0]}
        scale={2}
      />
    </group>
  )
}

useGLTF.preload('/table/table.gltf')
