/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alexis Ramos (https://sketchfab.com/lex_ram)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/poliform-bed-16070c2e6faa405391ab7ada8bb0aed6
Title: Poliform_Bed
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { FurnitureProps } from '../../types/gltf-types'

export function Bed2(props: FurnitureProps) {
  const { nodes, materials } = useGLTF('/bed_2/scene.gltf') as any

  if (!nodes || !materials) return null

  return (
    <group scale={0.05} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.mt_base_cama}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.mt_colchon_almuada}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.mt_edredon}
      />
    </group>
  )
}

useGLTF.preload('/bed_2/scene.gltf')
