export type Game = {
  id: number
  title: string
  thumbnail: string
  short_description: string
  game_url: string
  genre: string
  platform: string
  publisher: string
  developer: string
  release_date: string
  freetogame_profile_url: string
}

export const mockGetGamesResult: Game[] = [
  {
    id: 1,
    title: 'Counter-Strike 2',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Counter-Strike_2_logo.svg',
    short_description: 'Shooter tático em primeira pessoa focado em times.',
    game_url: 'https://store.steampowered.com/app/730/CounterStrike_2/',
    genre: 'Shooter',
    platform: 'PC',
    publisher: 'Valve',
    developer: 'Valve',
    release_date: '2023-09-27',
    freetogame_profile_url: 'https://www.freetogame.com/counter-strike-2',
  },
  {
    id: 2,
    title: 'League of Legends',
    thumbnail:
      'https://en.wikipedia.org/wiki/League_of_Legends#/media/File:League_of_Legends_2019_vector.svg',
    short_description: 'MOBA com batalhas 5v5 em Summoner’s Rift.',
    game_url: 'https://www.leagueoflegends.com/',
    genre: 'MOBA',
    platform: 'PC',
    publisher: 'Riot Games',
    developer: 'Riot Games',
    release_date: '2009-10-27',
    freetogame_profile_url: 'https://www.freetogame.com/league-of-legends',
  },
  {
    id: 3,
    title: 'Dota 2',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Dota_2_logo.svg',
    short_description: 'MOBA competitivo desenvolvido pela Valve.',
    game_url: 'https://store.steampowered.com/app/570/Dota_2/',
    genre: 'MOBA',
    platform: 'PC',
    publisher: 'Valve',
    developer: 'Valve',
    release_date: '2013-07-09',
    freetogame_profile_url: 'https://www.freetogame.com/dota-2',
  },
  {
    id: 4,
    title: 'Fortnite',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Fortnite_logo.png',
    short_description: 'Battle Royale com construção e modos criativos.',
    game_url: 'https://www.epicgames.com/fortnite/',
    genre: 'Battle Royale',
    platform: 'PC, Console, Mobile',
    publisher: 'Epic Games',
    developer: 'Epic Games',
    release_date: '2017-09-26',
    freetogame_profile_url: 'https://www.freetogame.com/fortnite',
  },
  {
    id: 5,
    title: 'Overwatch 2',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/en/8/89/Overwatch_2_Steam_artwork.jpg',
    short_description: 'Shooter em equipe com heróis únicos.',
    game_url: 'https://overwatch.blizzard.com/',
    genre: 'Shooter',
    platform: 'PC, Console',
    publisher: 'Blizzard Entertainment',
    developer: 'Blizzard Entertainment',
    release_date: '2022-10-04',
    freetogame_profile_url: 'https://www.freetogame.com/overwatch-2',
  },
  {
    id: 6,
    title: 'Minecraft',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Minecraft_cover.png',
    short_description: 'Sandbox de construção e sobrevivência em blocos.',
    game_url: 'https://www.minecraft.net/',
    genre: 'Sandbox',
    platform: 'PC, Console, Mobile',
    publisher: 'Mojang',
    developer: 'Mojang',
    release_date: '2011-11-18',
    freetogame_profile_url: 'https://www.freetogame.com/minecraft',
  },
  {
    id: 7,
    title: 'PUBG: Battlegrounds',
    thumbnail: 'https://en.wikipedia.org/wiki/File:PUBG_Battlegrounds_logo.svg',
    short_description: 'Battle Royale com foco em realismo e sobrevivência.',
    game_url: 'https://pubg.com/',
    genre: 'Battle Royale',
    platform: 'PC, Console',
    publisher: 'Krafton',
    developer: 'PUBG Studios',
    release_date: '2017-12-20',
    freetogame_profile_url: 'https://www.freetogame.com/pubg',
  },
  {
    id: 8,
    title: 'Valorant',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Valorant_logo.svg',
    short_description: 'Shooter tático com agentes e habilidades especiais.',
    game_url: 'https://playvalorant.com/',
    genre: 'Shooter',
    platform: 'PC',
    publisher: 'Riot Games',
    developer: 'Riot Games',
    release_date: '2020-06-02',
    freetogame_profile_url: 'https://www.freetogame.com/valorant',
  },
  {
    id: 9,
    title: 'World of Warcraft',
    thumbnail: 'https://en.wikipedia.org/wiki/File:World_of_Warcraft_logo.svg',
    short_description: 'MMORPG clássico ambientado em Azeroth.',
    game_url: 'https://worldofwarcraft.blizzard.com/',
    genre: 'MMORPG',
    platform: 'PC',
    publisher: 'Blizzard Entertainment',
    developer: 'Blizzard Entertainment',
    release_date: '2004-11-23',
    freetogame_profile_url: 'https://www.freetogame.com/world-of-warcraft',
  },
  {
    id: 10,
    title: 'Apex Legends',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Apex_legends_logo.png',
    short_description: 'Battle Royale em squads de heróis únicos.',
    game_url: 'https://www.ea.com/games/apex-legends',
    genre: 'Battle Royale',
    platform: 'PC, Console',
    publisher: 'Electronic Arts',
    developer: 'Respawn Entertainment',
    release_date: '2019-02-04',
    freetogame_profile_url: 'https://www.freetogame.com/apex-legends',
  },
  {
    id: 11,
    title: 'Call of Duty: Warzone',
    thumbnail:
      'https://en.wikipedia.org/wiki/File:Call_of_Duty_Warzone_logo.png',
    short_description: 'Battle Royale do universo Call of Duty.',
    game_url: 'https://www.callofduty.com/warzone',
    genre: 'Battle Royale',
    platform: 'PC, Console',
    publisher: 'Activision',
    developer: 'Infinity Ward',
    release_date: '2020-03-10',
    freetogame_profile_url: 'https://www.freetogame.com/warzone',
  },
  {
    id: 12,
    title: 'Genshin Impact',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Genshin_Impact_logo.svg',
    short_description: 'Ação RPG de mundo aberto com sistema gacha.',
    game_url: 'https://genshin.hoyoverse.com/',
    genre: 'Action RPG',
    platform: 'PC, Console, Mobile',
    publisher: 'HoYoverse',
    developer: 'HoYoverse',
    release_date: '2020-09-28',
    freetogame_profile_url: 'https://www.freetogame.com/genshin-impact',
  },
  {
    id: 13,
    title: 'Destiny 2',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Destiny_2_logo.png',
    short_description: 'Shooter de saque e ficção científica online.',
    game_url: 'https://www.bungie.net/7',
    genre: 'Shooter',
    platform: 'PC, Console',
    publisher: 'Bungie',
    developer: 'Bungie',
    release_date: '2017-09-06',
    freetogame_profile_url: 'https://www.freetogame.com/destiny-2',
  },
  {
    id: 14,
    title: 'Hearthstone',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Hearthstone_logo.svg',
    short_description: 'Card game online baseado no universo Warcraft.',
    game_url: 'https://playhearthstone.com/',
    genre: 'Card Game',
    platform: 'PC, Mobile',
    publisher: 'Blizzard Entertainment',
    developer: 'Blizzard Entertainment',
    release_date: '2014-03-11',
    freetogame_profile_url: 'https://www.freetogame.com/hearthstone',
  },
  {
    id: 15,
    title: 'Team Fortress 2',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Team_Fortress_2_logo.svg',
    short_description: 'Shooter em equipes com personagens caricatos.',
    game_url: 'https://store.steampowered.com/app/440/Team_Fortress_2/',
    genre: 'Shooter',
    platform: 'PC',
    publisher: 'Valve',
    developer: 'Valve',
    release_date: '2007-10-10',
    freetogame_profile_url: 'https://www.freetogame.com/team-fortress-2',
  },
  {
    id: 16,
    title: 'Rocket League',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Rocket_League_logo.svg',
    short_description: 'Futebol com carros turbo em arenas futuristas.',
    game_url: 'https://www.rocketleague.com/',
    genre: 'Sports',
    platform: 'PC, Console',
    publisher: 'Psyonix',
    developer: 'Psyonix',
    release_date: '2015-07-07',
    freetogame_profile_url: 'https://www.freetogame.com/rocket-league',
  },
  {
    id: 17,
    title: 'Fall Guys',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Fall_Guys_Logo.png',
    short_description: 'Party game com provas caóticas e engraçadas.',
    game_url: 'https://fallguys.com/',
    genre: 'Party',
    platform: 'PC, Console',
    publisher: 'Epic Games',
    developer: 'Mediatonic',
    release_date: '2020-08-04',
    freetogame_profile_url: 'https://www.freetogame.com/fall-guys',
  },
  {
    id: 18,
    title: 'Diablo IV',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Diablo_IV_logo.png',
    short_description: 'Action RPG sombrio com loot e dungeons.',
    game_url: 'https://diablo4.blizzard.com/',
    genre: 'Action RPG',
    platform: 'PC, Console',
    publisher: 'Blizzard Entertainment',
    developer: 'Blizzard Entertainment',
    release_date: '2023-06-05',
    freetogame_profile_url: 'https://www.freetogame.com/diablo-iv',
  },
  {
    id: 19,
    title: 'Grand Theft Auto V',
    thumbnail: 'https://en.wikipedia.org/wiki/File:GTA_V_logo.svg',
    short_description: 'Sandbox de ação em mundo aberto em Los Santos.',
    game_url: 'https://www.rockstargames.com/V/',
    genre: 'Action',
    platform: 'PC, Console',
    publisher: 'Rockstar Games',
    developer: 'Rockstar North',
    release_date: '2013-09-17',
    freetogame_profile_url: 'https://www.freetogame.com/gta-v',
  },
  {
    id: 20,
    title: 'The Witcher 3: Wild Hunt',
    thumbnail:
      'https://en.wikipedia.org/wiki/File:The_Witcher_3_Wild_Hunt_logo.png',
    short_description: 'RPG de mundo aberto estrelando Geralt de Rivia.',
    game_url: 'https://thewitcher.com/en/witcher3',
    genre: 'RPG',
    platform: 'PC, Console',
    publisher: 'CD Projekt',
    developer: 'CD Projekt Red',
    release_date: '2015-05-19',
    freetogame_profile_url: 'https://www.freetogame.com/witcher-3',
  },
  {
    id: 21,
    title: 'Elden Ring',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Elden_Ring_logo.svg',
    short_description: 'Action RPG em mundo aberto, criado por FromSoftware.',
    game_url: 'https://en.bandainamcoent.eu/elden-ring/elden-ring',
    genre: 'Action RPG',
    platform: 'PC, Console',
    publisher: 'Bandai Namco',
    developer: 'FromSoftware',
    release_date: '2022-02-25',
    freetogame_profile_url: 'https://www.freetogame.com/elden-ring',
  },
  {
    id: 22,
    title: 'Among Us',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Among_Us_logo.png',
    short_description: 'Jogo social de dedução em naves espaciais.',
    game_url: 'https://innersloth.com/gameAmongUs.php',
    genre: 'Party',
    platform: 'PC, Console, Mobile',
    publisher: 'Innersloth',
    developer: 'Innersloth',
    release_date: '2018-06-15',
    freetogame_profile_url: 'https://www.freetogame.com/among-us',
  },
  {
    id: 23,
    title: 'FIFA 23',
    thumbnail: 'https://en.wikipedia.org/wiki/File:FIFA_23_logo.svg',
    short_description: 'Simulação de futebol com licenças oficiais.',
    game_url: 'https://www.ea.com/games/fifa/fifa-23',
    genre: 'Sports',
    platform: 'PC, Console',
    publisher: 'EA Sports',
    developer: 'EA Vancouver',
    release_date: '2022-09-30',
    freetogame_profile_url: 'https://www.freetogame.com/fifa-23',
  },
  {
    id: 24,
    title: 'Halo Infinite',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Halo_Infinite_logo.png',
    short_description: 'Shooter sci-fi no universo Halo.',
    game_url: 'https://www.halowaypoint.com/halo-infinite',
    genre: 'Shooter',
    platform: 'PC, Xbox',
    publisher: 'Xbox Game Studios',
    developer: '343 Industries',
    release_date: '2021-12-08',
    freetogame_profile_url: 'https://www.freetogame.com/halo-infinite',
  },
  {
    id: 25,
    title: 'Cyberpunk 2077',
    thumbnail: 'https://en.wikipedia.org/wiki/File:Cyberpunk_2077_logo.svg',
    short_description: 'RPG futurista em mundo aberto.',
    game_url: 'https://www.cyberpunk.net/',
    genre: 'RPG',
    platform: 'PC, Console',
    publisher: 'CD Projekt',
    developer: 'CD Projekt Red',
    release_date: '2020-12-10',
    freetogame_profile_url: 'https://www.freetogame.com/cyberpunk-2077',
  },
]
